sudo: false

language: node_js

node_js:
  - '8'

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start; sleep 3; fi
  - npm install -g vsce

install:
  - npm install
  - npm run compile

script:
  - npm test

before_deploy:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then cd client && echo y | vsce package; fi
